---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: {{ .Values.namespace }}
data:
  storageClassMap: |
    sysdig:
       hostDir: /sysdig
       mountDir: /sysdig
       volumeMode: Filesystem
       fsType: ext4
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: {{ .Values.namespace }}
  labels:
    app: local-volume-provisioner
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      {{- if kindIs "map" .Values.nodeaffinityLabel }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeaffinityLabel.key }}
                operator: In
                values:
                - {{ .Values.nodeaffinityLabel.value }}
      {{- end }}
      serviceAccountName: local-storage-admin
      containers:
        - image: {{ .Values.airgapped_registry_name | default "quay.io" }}/external_storage/local-volume-provisioner:{{ .Values.sysdig.localVolumeProvisioner }}
          name: provisioner
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: quay.io/external_storage/local-volume-provisioner:v2.3.2
          volumeMounts:
            - mountPath: /etc/provisioner/config
              name: provisioner-config
              readOnly: true
            - mountPath: /dev
              name: provisioner-dev
            - mountPath: /sysdig
              name: sysdig
              mountPropagation: "HostToContainer"
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: sysdig
          hostPath:
            path: /sysdig

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-pv-binding
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-storage-provisioner-node-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-storage-provisioner-node-binding
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: local-storage-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
